version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:2701"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork
  
  mongoexpress:
    container_name: mongo-express
    image: mongo-express:0.54
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-conatiner
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - '8081:8081'
    volumes: 
      - mongodb_express_data:/data/db
    networks:
      - mynetwork

  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/Itinary1
      - NEO4JLABS_PLUGINS=['apoc', 'graph-data-science']
    volumes:
      - neo4j_data:/data
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongodb_data:
  neo4j_data:
  mongodb_express_data:

