version: "3.3"
services:
  oracle:
    image : container-registry.oracle.com/database/enterprise
    container_name: oracle-db
    environment:
      - ORACLE_PWD=Mafadu120c
    volumes:
      - /home/dugenou/oradata:/opt/oracle/oradata
    ports:
    - 1521:1521	
